[package]
name = "bitline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
argh = "0.1.10"
dialoguer = {version = "0.10.3", default-features = false}
hex = "0.4.3"
